version: "3.9"

services:
  webapp:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - webapp
    ports:
      - 80:8000
    volumes:
      - static-data:/vol/static

volumes:
  postgres-data:
  static-data: